### ISSUE TITLE
AttributeError: module 'xdg' has no attribute 'xdg_config_home'

### ISSUE THREAD

**Issue by bwagner** [sedrubal/leocli#1]
Attempting to fix with `pip install -U leocli` produced the same error.
Attempting with `pip install -U xdg` fixed it, even though there's an error during the installation:
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
leocli 3.4.3 requires xdg<6.0.0,>=5.1.1, but you have xdg 6.0.0 which is incompatible.
```
The capping `xdg<6.0.0,>`probably should be removed.

Python 3.11.4
leocli 3.4.3
macOS 13.4.1

**Comment by sedrubal** [comment]
Sorry for this issue and the late reply. Would you like to give some hints how you installed the package? And can you find the version of xdg that was installed in the first run? I can't find any recent version of the xdg package that does not include `xdg_config_home()`. However I'll update the dependencies soon.

**Comment by sedrubal** [comment]
Please test again with version 3.4.4 and feel free to reopen this issue if it still exists 😉
